// ═══════════════════════════════════════════
// CONDUCTOR — Token Exporter
// ═══════════════════════════════════════════

export function exportCSS(tokens) {
  let out = '/* Generated by CONDUCTOR */\n:root {\n';
  if (tokens.colors) for (const [k, v] of Object.entries(tokens.colors)) out += `  --color-${k}: ${v};\n`;
  if (tokens.spacing) tokens.spacing.forEach((v, i) => { out += `  --space-${i + 1}: ${v}px;\n`; });
  if (tokens.fontSizes) {
    const names = ['xs','sm','base','md','lg','xl','2xl','3xl','4xl','5xl','6xl'];
    tokens.fontSizes.forEach((v, i) => { out += `  --text-${names[i] || i}: ${v.size || v}px;\n`; });
  }
  if (tokens.radii) tokens.radii.forEach(r => { out += `  --radius-${r.name}: ${r.value >= 9999 ? '9999px' : r.value + 'px'};\n`; });
  if (tokens.shadows) tokens.shadows.forEach(s => { out += `  --shadow-${s.step}: ${s.css};\n`; });
  out += '}\n';
  return out;
}

export function exportTailwind(tokens) {
  const config = { theme: { extend: {} } };
  if (tokens.colors) config.theme.extend.colors = { ...tokens.colors };
  if (tokens.spacing) {
    config.theme.extend.spacing = {};
    tokens.spacing.forEach((v, i) => { config.theme.extend.spacing[String(i + 1)] = `${v}px`; });
  }
  if (tokens.fontSizes) {
    config.theme.extend.fontSize = {};
    const names = ['xs','sm','base','md','lg','xl','2xl','3xl','4xl','5xl','6xl'];
    tokens.fontSizes.forEach((v, i) => { config.theme.extend.fontSize[names[i] || i] = `${v.size || v}px`; });
  }
  if (tokens.radii) {
    config.theme.extend.borderRadius = {};
    tokens.radii.forEach(r => { config.theme.extend.borderRadius[r.name] = r.value >= 9999 ? '9999px' : `${r.value}px`; });
  }
  return `// tailwind.config.js — Generated by CONDUCTOR\nmodule.exports = ${JSON.stringify(config, null, 2)}\n`;
}

export function exportSCSS(tokens) {
  let out = '// Generated by CONDUCTOR\n\n';
  if (tokens.colors) for (const [k, v] of Object.entries(tokens.colors)) out += `$color-${k}: ${v};\n`;
  if (tokens.spacing) { out += '\n'; tokens.spacing.forEach((v, i) => { out += `$space-${i + 1}: ${v}px;\n`; }); }
  if (tokens.fontSizes) {
    out += '\n';
    const names = ['xs','sm','base','md','lg','xl','2xl','3xl','4xl','5xl','6xl'];
    tokens.fontSizes.forEach((v, i) => { out += `$text-${names[i] || i}: ${v.size || v}px;\n`; });
  }
  return out;
}

export function exportJSON(tokens) {
  return JSON.stringify(tokens, null, 2);
}

export function exportW3CTokens(tokens) {
  const w3c = {};
  if (tokens.colors) {
    w3c.color = {};
    for (const [k, v] of Object.entries(tokens.colors)) {
      w3c.color[k] = { $value: v, $type: 'color' };
    }
  }
  if (tokens.spacing) {
    w3c.spacing = {};
    tokens.spacing.forEach((v, i) => { w3c.spacing[`space-${i + 1}`] = { $value: `${v}px`, $type: 'dimension' }; });
  }
  if (tokens.fontSizes) {
    w3c.fontSize = {};
    const names = ['xs','sm','base','md','lg','xl','2xl','3xl','4xl','5xl','6xl'];
    tokens.fontSizes.forEach((v, i) => { w3c.fontSize[names[i] || i] = { $value: `${v.size || v}px`, $type: 'dimension' }; });
  }
  return JSON.stringify(w3c, null, 2);
}
